application: webapp2-user-authentication
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /signup
  script: main.app
  secure: always

- url: /css
  static_dir: css

- url: /scripts
  static_dir: scripts

- url: /images
  static_dir: images

- url: /login
  script: main.app
  secure: always

- url: /forgot
  script: main.app
  secure: always

- url: .*
  script: main.app


libraries:
- name: webapp2
  version: "2.5.1"
